TheLibrary/Controllers/API/BooksController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheLibrary.Data;
using TheLibrary.DTOs;
using TheLibrary.Models;

namespace TheLibrary.Controllers.API
{
	[Route("api/Books")]
	[ApiController]
	public class BooksController : ControllerBase
	{
		private TheLibraryDbContext _theLibraryDbContext;

		private readonly IMapper _mapper;

		public BooksController(IMapper mapper)
		{
			_theLibraryDbContext = new TheLibraryDbContext();
			_mapper = mapper;
		}

		[HttpGet]
		public ActionResult<IEnumerable<BookDTO>> GetBooks()
		{
			return _theLibraryDbContext.Books
				.Include(b => b.Genre)
				.Select(_mapper.Map<Book, BookDTO>)
				.ToList();
		}

		[HttpGet("{id}")]
		public ActionResult<BookDTO> GetBook(int id)
		{
			var book = _theLibraryDbContext.Books.SingleOrDefault(c => c.Id == id);

			if (book == null)
			{
				return NotFound();
			}

			return Ok(_mapper.Map<Book, BookDTO>(book));
		}

		[HttpPost]
		public ActionResult<BookDTO> CreateBook(BookDTO bookDTO)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest();
			}

			var book = _mapper.Map<BookDTO, Book>(bookDTO);

			_theLibraryDbContext.Books.Add(book);

			_theLibraryDbContext.SaveChanges();

			bookDTO.Id = book.Id;

			return Created(new Uri(Request.GetDisplayUrl() + "/" + bookDTO.Id), bookDTO);
		}

		[HttpPut("{id}")]
		public ActionResult UpdateBook(int id, BookDTO bookDTO)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest();
			}

			var bookInDb = _theLibraryDbContext.Books.SingleOrDefault(c => c.Id == id);

			if (bookDTO == null)
			{
				return NotFound();
			}

			_mapper.Map(bookDTO, bookInDb);

			_theLibraryDbContext.SaveChanges();

			return Ok();
		}

		[HttpDelete("{id}")]
		public ActionResult DeleteBook(int id)
		{
			var book = _theLibraryDbContext.Books.SingleOrDefault(c => c.Id == id);

			if (book == null)
			{
				return NotFound();
			}

			_theLibraryDbContext.Remove(book);

			_theLibraryDbContext.SaveChanges();

			return Ok();
		}
	}
}

TheLibrary/Controllers/API/CustomersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheLibrary.Data;
using TheLibrary.DTOs;
using TheLibrary.Models;

namespace TheLibrary.Controllers.API
{
	[Route("api/Customers")]
	[ApiController]
	public class CustomersController : ControllerBase
	{
		private TheLibraryDbContext _theLibraryDbContext;

		private readonly IMapper _mapper;

		public CustomersController(IMapper mapper)
		{
			_theLibraryDbContext = new TheLibraryDbContext();
			_mapper = mapper;
		}

		[HttpGet]
		public ActionResult<IEnumerable<CustomerDTO>> GetCustomers()
		{
			return _theLibraryDbContext.Customers
				.Include(c => c.MembershipType)
				.Select(_mapper.Map<Customer, CustomerDTO>)
				.ToList();
		}

		[HttpGet("{id}")]
		public ActionResult<CustomerDTO> GetCustomer(int id)
		{
			var customer = _theLibraryDbContext.Customers.SingleOrDefault(c => c.Id == id);

			if(customer == null)
			{
				return NotFound();
			}

			return Ok(_mapper.Map<Customer, CustomerDTO> (customer));
		}

		[HttpPost]
		public ActionResult<CustomerDTO> CreateCustomer(CustomerDTO customerDTO)
		{
			if(!ModelState.IsValid)
			{
				return BadRequest();
			}

			var customer = _mapper.Map<CustomerDTO, Customer>(customerDTO);

			_theLibraryDbContext.Customers.Add(customer);

			_theLibraryDbContext.SaveChanges();

			customerDTO.Id = customer.Id;

			return Created(new Uri(Request.GetDisplayUrl() + "/" + customerDTO.Id), customerDTO);
		}

		[HttpPut("{id}")]
		public ActionResult UpdateCustomer(int id, CustomerDTO customerDTO)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest();
			}

			var customerInDb = _theLibraryDbContext.Customers.SingleOrDefault(c => c.Id == id);

			if (customerDTO == null)
			{
				return NotFound();
			}

			_mapper.Map(customerDTO, customerInDb);

			_theLibraryDbContext.SaveChanges();

			return Ok();
		}

		[HttpDelete("{id}")]
		public ActionResult DeleteCustomer(int id)
		{
			var customer = _theLibraryDbContext.Customers.SingleOrDefault(c => c.Id == id);

			if (customer == null)
			{
				return NotFound();
			}

			_theLibraryDbContext.Remove(customer);

			_theLibraryDbContext.SaveChanges();

			return Ok();
		}
	}
}

TheLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheLibrary.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/datatables/css/dataTables.bootstrap.css"/>
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TheLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="~/datatables/js/dataTables.bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TheLibrary/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>